version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "dependencies"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "python"
      - "dependencies"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      # Ignore major version updates for these packages
      - dependency-name: "bandit"
        update-types: ["version-update:semver-major"]
      - dependency-name: "flake8"
        update-types: ["version-update:semver-major"]
